SCREEN_WIDTH = 160
SCREEN_HEIGHT = 120
STONE_INTERVAL = 17
ITEM_INTERVAL = 3
NAME_SCENE = "name"
START_SCENE = "start"
PLAY_SCENE = "play"
LEADERBOARD_SCENE = "leaderboard"

STONE_SPEED = 0.8
PLAYER_SPEED = 2.5
ITEM_SPEED = 0
PLAY_SCREEN_COLOR= "pyxel.COLOR_BROWN"
IS_WEB = False
