SCREEN_WIDTH = 160
SCREEN_HEIGHT = 120
STONE_INTERVAL = 17
NAME_SCENE = "name"
START_SCENE = "start"
PLAY_SCENE = "play"
LEADERBOARD_SCENE = "leaderboard"

STONE_SPEED = 0.8
PLAYER_SPEED = 3.0

PLAY_SCREEN_COLOR= "pyxel.COLOR_BROWN"
IS_WEB = True
